export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_ITEM_EDITING = 'SET_ITEM_EDITING';